version: '1'
services:
  lattemaid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lattemaid-bot
    volumes:
      - ./lattemaid:/app
    working_dir: /app
    env_file: .env
    restart: unless-stopped